name       : xkeyboard-config
version    : 2.19
release    : 5
source     :
    - https://www.x.org/releases/individual/data/xkeyboard-config/xkeyboard-config-2.19.tar.gz : f278c3ef6939122e727dab48e06f08916b09e5cfe1837fbfe6b0f69af96a8048
license    : MIT
component  : xorg.base
summary    : Keyboard configuration database
description: |
    The XKeyboardConfig package contains the keyboard configuration database for the X Window System.
builddeps  :
    - pkgconfig(x11)
setup      : |
    %configure --disable-static \
        --with-xkb-rules-symlink=xorg
build      : |
    %make
install    : |
    %make_install
