name       : xkeyboard-config
version    : '2.28'
release    : 11
source     :
    - https://www.x.org/releases/individual/data/xkeyboard-config/xkeyboard-config-2.28.tar.bz2 : 69adb25b0fc64e4075f8ec0eab8d869892419f474f91fb69db1713de2062bdce
license    : MIT
component  : xorg.base
summary    : Keyboard configuration database
description: |
    The XKeyboardConfig package contains the keyboard configuration database for the X Window System.
builddeps  :
    - pkgconfig(x11)
setup      : |
    %configure --with-xkb-rules-symlink=xorg
build      : |
    %make
install    : |
    %make_install
