name       : xkeyboard-config
version    : '2.39'
release    : 13
source     :
    - https://www.x.org/releases/individual/data/xkeyboard-config/xkeyboard-config-2.39.tar.xz : 5ac5f533eff7b0c116805fe254fd79b2c9882700a4f9f2c070f8c4eae5aaa682
license    : MIT
component  : xorg.base
summary    : Keyboard configuration database
description: |
    The XKeyboardConfig package contains the keyboard configuration database for the X Window System.
builddeps  :
    - pkgconfig(x11)
setup      : |
    %meson_configure -Dxorg-rules-symlinks=true
build      : |
    %ninja_build
install    : |
    %ninja_install
