name       : xkeyboard-config
version    : '2.24'
release    : 7
source     :
    - https://www.x.org/releases/individual/data/xkeyboard-config/xkeyboard-config-2.24.tar.gz : 21276860a413ca351a781732d729b35cdc5800151e7759f1679036b1b16cdd2a
license    : MIT
component  : xorg.base
summary    : Keyboard configuration database
description: |
    The XKeyboardConfig package contains the keyboard configuration database for the X Window System.
builddeps  :
    - pkgconfig(x11)
setup      : |
    %configure --with-xkb-rules-symlink=xorg
build      : |
    %make
install    : |
    %make_install
