name       : xkeyboard-config
version    : '2.25'
release    : 8
source     :
    - https://www.x.org/releases/individual/data/xkeyboard-config/xkeyboard-config-2.25.tar.gz : a777b62b926351c1398e388b61d144c4f0ff2266186d09d7223107d8e96a7bd2
license    : MIT
component  : xorg.base
summary    : Keyboard configuration database
description: |
    The XKeyboardConfig package contains the keyboard configuration database for the X Window System.
builddeps  :
    - pkgconfig(x11)
setup      : |
    %configure --with-xkb-rules-symlink=xorg
build      : |
    %make
install    : |
    %make_install
